### ISSUE TITLE
Configurable buttons labels

### ISSUE THREAD

**Issue by Tolriq** [jaredrummler/ColorPicker#10]
Hi,

First thanks for this very nice library that perfectly fit my needs :)

Do you think that you can make the dialog buttons configurable like the dialog title?
Reason is that most of the buttons strings are already translated in many languages in my app, that use external translations tools.

Avoiding necessary strings and allowing more complete names to help translators would be really cool.

**Comment by jaredrummler** [comment]
See #23

932371a2e5ae9970fae15b2b6e7ee3340e59c09a
