### ISSUE TITLE
strange dialog behavior on attach

### ISSUE THREAD

**Issue by BlackDizel** [jaredrummler/ColorPicker#13]
In `com.jrummyapps.android.colorpicker.ColorPickerDialog#onAttach`:

This strange code works properly only on some situations:

```java
if (colorPickerDialogListener == null && activity instanceof ColorPickerDialogListener) {
    colorPickerDialogListener = (ColorPickerDialogListener) activity;
}
```

**Comment by jaredrummler** [comment]
You need to either have your activity implement `ColorPickerDialogListener` or use `setColorPickerDialogListener` before showing the dialog. What situations don't work for you?
