### ISSUE TITLE
  如何获取 透明度 How to get transparency？

### ISSUE THREAD

**Issue by qssq** [jaredrummler/ColorPicker#25]
I want to turn transparency and three colors into 16 - ary code, but I don't know how to get transparency, and the callback doesn't return transparency

**Comment by jaredrummler** [comment]
I think this is what you are looking for: https://developer.android.com/reference/android/graphics/Color.html#alpha(int)

**Comment by qssq** [comment]
thank ,i donknow use ,because show exception,
    @NonNull
    private String getHexColorByIntColor(boolean needAppendAlpha) {
        String defaultAlpha = "ff";
        if (needAppendAlpha) {
            try {
                Field fieldAplha = colorPickerView.getClass().getDeclaredField("alpha");
                fieldAplha.setAccessible(true);
                int o = fieldAplha.getInt(colorPickerView);
                defaultAlpha = Integer.toHexString(o);
            } catch (NoSuchFieldException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }

        } else {
            defaultAlpha = "";
        }
        return toHexEncoding(colorPickerView.getColor(), defaultAlpha);
    }


    public static String toHexEncoding(int color, String defaultAlpha) {
        String R, G, B, A;
        StringBuffer sb = new StringBuffer();
        A = color + "".length() == 8 ? Integer.toHexString(Color.alpha(color)) : "" + defaultAlpha;
        R = Integer.toHexString(Color.red(color));
        G = Integer.toHexString(Color.green(color));
        B = Integer.toHexString(Color.blue(color));
        //判断获取到的R,G,B值的长度 如果长度等于1 给R,G,B值的前边添0
        A = A.length() == 1 ? "0" + A : A;
        R = R.length() == 1 ? "0" + R : R;
        G = G.length() == 1 ? "0" + G : G;
        B = B.length() == 1 ? "0" + B : B;
        sb.append("#");
        sb.append(A);
        sb.append(R);
        sb.append(G);
        sb.append(B);
        return sb.toString();
    }
