### ISSUE TITLE
It does not work with android.support.v7.preference.Preference

### ISSUE THREAD

**Issue by jrcacd** [jaredrummler/ColorPicker#26]

**Comment by paour** [comment]
```
android.view.InflateException: Binary XML file line #0: Error inflating class com.jaredrummler.android.colorpicker.ColorPreference
    at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:258)
    at android.support.v7.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:287)
    at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:354)
    at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:356)
    at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:162)
    at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
    at android.support.v7.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:138)
    at android.support.v7.preference.PreferenceManagerFix.inflateFromResource(PreferenceManagerFix.java:59)
    at android.support.v7.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:432)
    at com.frogsparks.mytrails.Preferences$MyPreferenceFragment.onCreatePreferencesFix(Preferences.java:759)
    at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:53)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:2329)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
    at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
    at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
    at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)

09-23 10:41:31.807 12310-12310/com.frogsparks.mytrails.debug21 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassCastException: com.jaredrummler.android.colorpicker.ColorPreference cannot be cast to android.support.v7.preference.Preference
    at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:251)
```

**Comment by paour** [comment]
Creating `DialogPreference`s with the support preferences library [is a lot of work](https://stackoverflow.com/a/32812614/304876). It can be done, but still requires some plumbing in the app to map the `DialogPreference` to a `PreferenceDialogFragmentCompat`. This is made slightly easier by the [support preference fix library](https://github.com/Gericop/Android-Support-Preference-V7-Fix) (`PreferenceFragmentCompat.addDialogPreference`).

Still, it's easier to just handle the `onPreferenceTreeClick(Preference preference)` and show the dialog in your `PreferenceFragmentCompat`.

I've made a [small modification](https://gist.github.com/paour/4ad4d49822816131c236dbe6d2af94bf) to `ColorPreference` which can be included in this project for users of the preference compat library.

**Comment by paour** [comment]
@jaredrummler if you're interested, I can create a PR to document how to use the library with the support preference library, and implement the changes in `ColorPreference` I was referring to.

**Comment by pawelantczak** [comment]
@jaredrummler do you plan to add support for compat library? @paour any update with PR?
Thanks.

**Comment by paour** [comment]
@pawelantczak I try not to waste my time tidying up PRs that end up being ignored by unmaintained projets, but I can send you the relevant files if you wish.

**Comment by pawelantczak** [comment]
@paour you are right. I ended up using this lib as color picker and https://github.com/kizitonwose/colorpreference as preference view.
Thanks.

**Comment by 835700012** [comment]
there is a only question,How should I get the ColorPreference's color when user changed the default value,
for example,the native EditTextPreference may use like this:
EditTextPreference edit_ref1 = (EditTextPreference) findPreference("edit_ref1");
String txt = edit_ref1.getText();

but in our ColorPreference the color of the member is private ,May I need to add a public method like
int getColor()
{
    return color;
}
in the ColorPreference class?
thanks a lot.

**Comment by pawelantczak** [comment]
@835700012 
```mColorPreferenceCompat.setValue(color);```
as per https://github.com/kizitonwose/colorpreference#custom-picker-sample

**Comment by 835700012** [comment]
@pawelantczak 
thanks for your reply,
but I need not to build a custom dialog and override the method onColorSelected(the 1st param is the dialog id.)
the link u show me is the same function onColorSelected(the 2nd param isString tag to indicate the source 'control')
so, I can not find the right way to get the color in the PreferenceCategory....

**Comment by 835700012** [comment]
I mean I use the default color picker dialog,my code is the same as the demo,so simply but I can not get the way to get the ColorPreference item color,thanks a lot again .

**Comment by pawelantczak** [comment]
@835700012 
Why not simply get/set it via preference key?

**Comment by 835700012** [comment]
@pawelantczak 
my code 
ColorPreference cp1 = (ColorPreference) findPreference("my key");
ColorPreference do not have any method to access the color,what a pity.....

**Comment by pawelantczak** [comment]
@835700012 How will you use the color user picked?
Via shared preferences. You defined "key" in your xml and you are able to use same key to receive what users picked.
Take a look here: https://stackoverflow.com/questions/2614719/how-do-i-get-the-sharedpreferences-from-a-preferenceactivity-in-android

**Comment by 835700012** [comment]
@pawelantczak 
I mean in ColorPreference class do not have any method to access the color,should I add a new funtion to return the color ?
thanks for ur reply.

**Comment by pawelantczak** [comment]
@835700012 I know.
You don't need to have direct access to selected color.
Every preference works the same way.
In XML definition you have something like this:

``` android:key="color_picked"```

Android will automatically store value of each preference into shared preferences.
When you want to read what user has picked, you need to use shared preferences.
```
SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
// then you use
prefs.getInt("color_picked", 0);
```

**Comment by 835700012** [comment]
@pawelantczak 
thanks a lot, I get the color with ur great help finally !

**Comment by 835700012** [comment]
@pawelantczak 
hi, I am coming again,could u please be so kind to tell me how to set the color to the item ColorPreference?
I can not find any way to set the color as opposite prefs.setInt("my Id", value)....
thanks again!

**Comment by kizitonwose** [comment]
@835700012 ColorPreference has `getValue()` and `setValue(int)` methods which you can use to get and set the color value respectively. This also updates the preference view with the new color.

**Comment by h6ah4i** [comment]
Hi, I have created a forked version of this library which uses `android.support.v7.preference.Preference`.

https://github.com/h6ah4i/ColorPicker

**Comment by AndroidDeveloperLB** [comment]
I've created a fork that uses even the newer API, of PreferenceFragmentCompat :

https://github.com/AndroidDeveloperLB/ColorPicker

**Comment by kilicpl** [comment]
As briefly mentioned once a color chosen it s automatically saved to sharedpreferences . So to get the color your just need to do
                int color = android.preference.PreferenceManager.getDefaultSharedPreferences(getActivity()).getInt("your_key_name_in_preferencesxml", Color.YELLOW);

if you want you can use that color fırther 
getColorHex(color)   
to get the hex code to be able to use according to your needs

**Comment by kilicpl** [comment]
But now I have a question:)
In preferencefragment    setOnPreferenceClickListener onClick method when we use 
int color = android.preference.PreferenceManager.getDefaultSharedPreferences(getActivity()).getInt("color_preference", Color.YELLOW);

we get the previous color from the last color choose. How can we get the current chosen color in the sharedpreferences? Thank you

**Comment by AndroidDeveloperLB** [comment]
@kilicpl Isn't it the same as all Preference classes, meaning this:
https://developer.android.com/reference/android/preference/Preference.OnPreferenceChangeListener

There you can check the previous and the new value, at least for other types of preferences.

**Comment by kilicpl** [comment]
Yes  you are extremely right AndroidDeveloperLB, my confusion. The working code in YourPreferenceHoldingFragment would be like:

 public boolean onPreferenceChange(Preference preference, Object newValue) {
       mPreferences = PreferenceManager.getDefaultSharedPreferences(getActivity());
       int color= 
 android.preference.PreferenceManager.getDefaultSharedPreferences(getActivity()).getInt("your_key_name_in_preferencesxml", Color.YELLOW);
                 
         SharedPreferences.Editor preferencesEditor = mPreferences.edit();
         preferencesEditor.putInt("color_preference", (Integer)newValue);
        preferencesEditor.apply();
        return true;
     }
 });


Still i m curious how to use with getValue().. Many thanks to creator of this awesome library btw 👍

**Comment by jaredrummler** [comment]
I may be a year late, but support for has been added.

Simply use:

```groovy
implementation 'com.jaredrummler:colorpicker-compat:1.0.3'
```

See the demo for example usage.
