### ISSUE TITLE
Dialog Layout doesn't fit in Landscape

### ISSUE THREAD

**Issue by arsenioo** [jaredrummler/ColorPicker#27]
Samsung N7000, API 16+. Color picker dialog does not fit vertically when device is Landscape, the color selection area is too big (see scrollbars when scrolled to the bottom). The screen resolution is 1280x800, stock firmware, no large font or any accessibility options, etc.

![picker-bug](https://user-images.githubusercontent.com/32209647/30767270-871e4356-9ffb-11e7-801c-dbeecd84eb96.png)

**Comment by jaredrummler** [comment]
I am aware of this and that is why the view is in a ScrollView. Do you have any suggestions on how to improve this? Pull requests are welcome.

**Comment by codeage** [comment]
You can modify the color sample size in dimen.xml
![image](https://user-images.githubusercontent.com/1198545/32051410-1a9410a6-ba1a-11e7-992a-4abefcdc0ad4.png)
`<?xml version="1.0" encoding="utf-8"?>
<resources>
  <dimen name="cpv_required_padding">6dp</dimen>
  <dimen name="cpv_dialog_preview_width">66dp</dimen>
  <dimen name="cpv_dialog_preview_height">34dp</dimen>
  <dimen name="cpv_column_width">30dp</dimen>
  <dimen name="cpv_item_size">20dp</dimen>
  <dimen name="cpv_item_horizontal_padding">4dp</dimen>
  <dimen name="cpv_color_preference_normal">28dp</dimen>
  <dimen name="cpv_color_preference_large">40dp</dimen>
</resources>
`

**Comment by jaredrummler** [comment]
Closing for now. Will review a PR and the dialog does use a ScrollView or you can override the dimensions as suggested. Thanks.
