### ISSUE TITLE
onColorSelected doesn't work

### ISSUE THREAD

**Issue by valeriogiocondi** [jaredrummler/ColorPicker#32]
Looks like onColorSelected is never called, neither when i press "select button" or double-click on colors.

I also implemented ColorPickerDialogListener into fragmente-generator-activity, but nothing happened.

```
public class Fragment_ColorPicker extends PreferenceFragment implements ColorPickerDialogListener {

    public Fragment_ColorPicker() {
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.color_preferences);
    }

    @Override
    public void onColorSelected(int dialogId, @ColorInt int color) {

        System.out.println("Hello");
    }

    @Override
    public void onDialogDismissed(int dialogId) {

    }
}
```

Could you help me, please?

**Comment by jaredrummler** [comment]
The `ColorPreference` implements `ColorPickerDialogListener` and is called to update the preference. Instead of using a `ColorPickerDialogListener`, you can add a `OnPreferenceChangeListener` as shown below:

```java
ColorPreference colorPreference = (ColorPreference) findPreference("REPLACE_WITH_KEY");
colorPreference.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
  @Override public boolean onPreferenceChange(Preference preference, Object newValue) {
    if ("REPLACE_WITH_KEY".equals(preference.getKey())) {
      String newDefaultColor = Integer.toHexString((int) newValue);
      Log.d(TAG, "New default color is: #" + newDefaultColor);
    }
    return true;
  }
});
```

**Comment by valeriogiocondi** [comment]
I'm sorry, I did not explain well, I just need to get color selected from picker, and you describe (in your source code) ColorPickerDialogListener.onColorSelected as the method I'm looking for:

  /*
   **Callback that is invoked when a color is selected from the color picker dialog.**
   *
   * @param dialogId
   *     The dialog id used to create the dialog instance.
   * @param color
   *     The selected color
   */
`  void onColorSelected(int dialogId, @ColorInt int color);`

**Comment by jaredrummler** [comment]
I'm assuming you are using `ColorPreference`. You don't need the `ColorPickerDialogListener` if you are using the `ColorPreference`. If the user changes the color then you can use `onPreferenceChange` as shown above.

**Comment by valeriogiocondi** [comment]
I get it. I took the demo as example, that's why I used onColorSelected. 

Which is the key to replace "REPLACE_WITH_KEY"?

**Comment by valeriogiocondi** [comment]
I get it. I took the demo as example, that's why I used onColorSelected. 

Thanks a lot, your colorPicker is awesome :)
