### ISSUE TITLE
Cannot setColorPickerDialogListener

### ISSUE THREAD

**Issue by 7200rpm** [jaredrummler/ColorPicker#35]
I would like to be able to set my own listener so that the included Activity does not need to listen for the color result. Something like this:

```kotlin
var dlg = ColorPickerDialog.newBuilder()
dlg.setColorPickerDialogListener(object : ColorPickerDialogListener{

    override fun onColorSelected(dialogId: Int, color: Int) {
        mood_color_text.setTextColor(color)
    }

    override fun onDialogDismissed(dialogId: Int) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }
})
```

I notice that I can use `setColorPickerDialogListener` when I don't use the builder, but then I can't figure out how to set all the parameters and load it correctly. What is the best way to set my listener? Thanks.

**Comment by JRoot3D** [comment]
var dlg = ColorPickerDialog.newBuilder().create()

**Comment by oscarg798** [comment]
I just create this  [pull request ](https://github.com/jaredrummler/ColorPicker/pull/36)  to allow pass the listener to the builder

**Comment by jaredrummler** [comment]
For now, set the listener after you create the dialog as JRoot3D suggested. Thanks.
