### ISSUE TITLE
Add Support for Wallpaper Colors

### ISSUE THREAD

**Issue by rgocal** [jaredrummler/ColorPicker#56]
Would their be a way to create a pallette of colors based on the device's current wallpaper?

Below with the options in the dialog or a button to get wallpaper colors and the pallette of colors be of those with tint options or based on specific dominant colors. 

This could be done with either getting the current wallpaper and converting it into a bitmap than using color pallette lib to pull colors or this new Android P wallpaper Colors API?

**Comment by AndroidDeveloperLB** [comment]
Not related to the library. You can do it yourself:

https://developer.android.com/reference/android/app/WallpaperManager#getWallpaperFile(int)
https://developer.android.com/reference/android/app/WallpaperManager#getDrawable()

https://developer.android.com/reference/android/app/WallpaperColors#fromBitmap(android.graphics.Bitmap)
https://developer.android.com/reference/android/app/WallpaperColors#fromDrawable(android.graphics.drawable.Drawable)
