### ISSUE TITLE
ColorPickerDialog color circles are blank (0% alpha I think)

### ISSUE THREAD

**Issue by jpsemery** [jaredrummler/ColorPicker#59]
Hi I started using your color picker in my preferences and it work very well I must say. 
I have an listview if items with a button to call the ColorPickerDialog like this

```
      private void showColorPickerDialog(int id,  int color) {
		ColorPickerDialog dialog = ColorPickerDialog.newBuilder()
				.setDialogId(id)
				.setColor(color)
				.setSelectedButtonText(android.R.string.ok)
				.create();

		dialog.setColorPickerDialogListener(this);
		dialog.show(mContext.getFragmentManager(), "Color_picker");
    }

```
the problem is that all the color circles are blank i.e. they show the white / grey grid wich seems to indicate that every color in 0% alpha. the circle outlines do  show color.
The custom screen also shows the two color boxes as blank.

I fiddled around with options and looked at your source code but could not find any thing.
 
Any Idea what would cause this?
If I cannot resolve this I will have to use another color picker all together since it does not make sense to use two different ones in the same applications

Thanks a lot for your help and very nice work BTW

**Comment by jaredrummler** [comment]
Most likely the color has alpha. Try stripping the alpha from the color:

```java
color = Color.rgb(Color.red(color), Color.green(color), Color.blue(color));
```

**Comment by ronenfe** [comment]
I have the same problem, i posted a screenshot in the bug, it works only on android 35. The palette itself all have the checkerboard.
