### ISSUE TITLE
Failed to resolve: ColorPicker:colorpicker:unspecified

### ISSUE THREAD

**Issue by zacharee** [jaredrummler/ColorPicker#63]
Implementing the compat library (v1.0.4) causes this error when attempting to sync the project.

Implementation:

    implementation 'com.jaredrummler:colorpicker-compat:1.0.4'

Error:

    Failed to resolve: ColorPicker:colorpicker:unspecified
    Open File
    Show in Project Structure dialog

Dependency tree:

    \--- com.jaredrummler:colorpicker-compat:1.0.4
         +--- ColorPicker:colorpicker:unspecified FAILED
         \--- androidx.preference:preference:1.0.0 (*)

Also happens on:
 - 1.0.3

Normal version syncs fine.

**Comment by jaredrummler** [comment]
Sorry about that. Fixed in 1.0.5.
