### ISSUE TITLE
I'm probably just dumb but...

### ISSUE THREAD

**Issue by Silvanor42** [jaredrummler/ColorPicker#69]
I have no idea how to get this working. I've tried so many things but they all fail. I'm pretty new to android app development so bear with me. So just putting implementation 'com.jaredrummler:colorpicker:1.0.5' in my gradle file won't compile. I first have to convert everything to androidx. Alright, i've found that one out. But then I made an preference xml to test it but when i use for instance:
 ` <com.jaredrummler.android.colorpicker.ColorPreference
            android:defaultValue="0xFFEC407A"
            android:key="custom_only_color"
            android:summary="A picker that doesn't show the presets"
            android:title="Custom color"`
It won't give a preview. I also tried the compat version and all other kinds of stuff but i can't figure out how to do it. Is there a step I'm missing?

**Comment by SapuSeven** [comment]
First of all, please use more meaningful titles for your issues.

Second, you need to post logs or at least error messages. Otherwise, it is really hard to figure out the cause of your problem.

**Comment by jaredrummler** [comment]
Will re-open if more details are provided. thanks.
